### ISSUE TITLE
MaxGCPauseMillis JVM Option

### ISSUE THREAD

**Issue by JeffCarpenter** [ixy-languages/ixy.java#4]
I see that you have MaxGCPauseMillis set to 1 in ixy-pktgen.sh and ixy-pktfwd.sh. From what I've gathered from JVM experts (and their slide decks), generally you get better results setting MaxGCPauseMillis to about 1000. AFAIK all the parameter actually does is adjust the heap size, so setting it to 1 would get you a really small heap. That being said it looks like you are doing some manual memory management, so maybe having a small heap isn't hurting your performance much.

**Comment by emmericp** [comment]
We've tried higher values, but there wasn't a difference for throughput.
